version: "3.3"
services:
  server:
    image: shivajreddy/concha-api:latest
    depends_on:
      - postgres
    ports:
      - "80:${SERVER_PORT}"
    env_file:
      - ./.env
    command: bash -c "uvicorn server:app --host ${SERVER_ADDRESS} --port ${SERVER_PORT} --reload"

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: