version: "3.3"
services:
  server:
    image: shivajreddy/concha-api:latest
    ports:
      - "80:${SERVER_PORT}"
    env_file:
      - ./.env

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: