version: "3.8"
services:
  dev-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: uvicorn server:app --host ${SERVER_ADDRESS} --port ${SERVER_PORT} --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: