version: "3.8"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    env_file:
      - ./.env
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=conchadb
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
