"""first revision: creating tables with model schema

Revision ID: 415709c2ad94
Revises: 
Create Date: 2022-11-02 22:28:12.421056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415709c2ad94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_data',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ticks', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('selected_tick', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
