"""adding password column to user table

Revision ID: d798b2133d7e
Revises: 1e5b8ae8386c
Create Date: 2022-10-28 00:41:59.126655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd798b2133d7e'
down_revision = '1e5b8ae8386c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_data', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'audio_data', 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_data', type_='foreignkey')
    op.drop_column('audio_data', 'user_id')
    # ### end Alembic commands ###
