"""first revision: Make all tables

Revision ID: 22e878ba4f68
Revises: 
Create Date: 2022-10-20 11:08:22.273574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e878ba4f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_data_file',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ticks', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('selected_tick', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('audio_data_file')
    # ### end Alembic commands ###
